#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [28]:
import numpy as np

arr = np.array((7, 8, 4, 5, 1, 2))
print(arr)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [4]:
import numpy as np
arr = np.array((7, 8, 4, 5, 1, 2))
print(arr[2:])

[4 5 1 2]


Using slicing print all the elements except the last one.



In [5]:
import numpy as np
arr = np.array((7, 8, 4, 5, 1, 2))
print(arr[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [8]:
import numpy as np
arr = np.array((7, 8, 4, 5, 1, 2))
print(arr[:4])

[7 8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [11]:
import numpy as np

arr = np.array((7,8,4,5,1,2))
arre  = arr.reshape(3,2)
print(arre)

[[1 2]
 [3 4]
 [5 6]]


Print all the array elements one by one (iterating).



In [14]:
import numpy as np

arr = np.array((7, 8, 4, 5, 1, 2))
for x in arr:
  print(x)

1
2
3
4
5
6


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [0]:
import numpy as np

arr = np.array((0, 6, 9))
print(arr)

Join the two arrays.



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
arr2 = np.array([0,6,9])
FinalArr = np.concatenate((arr,arr2))
print(FinalArr)

Using filtering print only the odd numbers of the joined array.



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2,0,6,9])
filterarr = []
x = [True, False, True, False, True, False, True, False, True]
newarr = arr[x]
print(newarr)

Sort the joined array elements.



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2,0,6,9])
arraysorted = np.sort(arr, axis = None)
print(arraysorted)

Store in an array the names of the months.



In [0]:
import numpy as np
arrMonths = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'Agaust' , 'September', 'October', 'November', 'December'])
print(arrMonths)

Split the months array in 4 periods of 3 elements each one.



In [0]:
import numpy as np
arrMonths = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'Agaust' , 'September', 'October', 'November', 'December'])
splitedArrayMonths = np.split(arrMonths, 3)
print(splitedArrayMonths)

Create an array with genre information ['F','M','F','F','M','F'].



In [17]:
import numpy as np

arr = np.array(('F','M','F','F','M','F'))
print(arr)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [25]:
import numpy as np
arr = np.array(('F','M','F','F','M','F'))
y=0
for x in arr:
  if x == 'F':
    print(y)
  y= y+1    


0
2
3
5


Store in an array the age information [18,20,19,23,19,20].



In [0]:
import numpy as np
ageInformation = np.array([18,20,19,23,19,20])
print(ageInformation)

Create a filter array with values < 20.



In [0]:
import numpy as np
ageInformation = np.array([18,20,19,23,19,20])
for element in ageInformation:
  if element <= 20:
    np.append(ageInformation, True)
  else:
    np.append(ageInformation, False)
print(ageInformation)


Change the 3 index element with a value of 22



In [26]:
import numpy as np
arr = np.array((18,20,19,23,19,20))
arr[2] = 22
print(arr)

[18 20 22 23 19 20]


Print the 4 index element.

In [27]:
import numpy as np
arr = np.array((18,20,19,23,19,20))
print(arr[3])

23
